use std::{
    collections::{BTreeMap, BTreeSet},
    sync::{Arc, Mutex},
};

use assert2::check;
use krabka_blockstore::Labels;
use krabka_metrics::{SamplePayload, WalRecord};
use krabka_units::prelude::*;

use crate::{EngineOpts, InMemoryMetricStore, PromqlEngine};

// === split-modules: generated submodules ===
mod alerting_rule_dispatch_expands_value_and_labels_templates;
mod alerting_rule_dispatch_sends_firing_alerts_to_alertmanager_sink;
mod alerting_rule_dispatch_waits_for_for_duration_before_sending;
mod alerting_rule_group_dispatch_runs_alerts_and_skips_recording_rules;
mod alerting_rule_state_persistence_records_active_and_cleared_alerts;
mod alerting_rule_with_compound_for_does_not_fire_immediately;
mod alerting_rule_with_negative_for_is_a_hard_error;
mod firing_alert_emits_resolved_when_series_stops_matching;
mod keep_firing_for_holds_alert_firing_then_resolves_after_window;
mod labels;
mod parse_duration_supports_all_units_and_compounds_and_rejects_bad_input;
mod recording_alertmanager_sink;
mod recording_rule_append_writes_materialized_records_to_sink;
mod recording_rule_evaluation_materializes_float_samples_as_wal_records;
mod recording_rule_fails_on_labelset_collision_after_rule_labels;
mod recording_rule_group_append_runs_recording_rules_and_skips_alerts;
mod recording_rule_merges_rule_level_labels_into_every_series;
mod recording_ruler_state_sink;
mod recording_sink;
mod ruler_alert_state_replays_compacted_records_before_evaluation;
mod ruler_group_state_replays_compacted_last_eval_records;
mod ruler_rule_group_evaluation_appends_recordings_and_dispatches_firing_alerts;
mod ruler_rule_set_evaluation_persists_group_last_eval_state;
mod ruler_rule_set_evaluation_runs_namespaced_groups;
mod ruler_rule_set_filter_combines_shard_ownership_and_due_evaluation;
mod ruler_rule_set_filter_keeps_only_groups_due_for_evaluation;
mod ruler_rule_set_filter_partitions_groups_by_tenant_namespace_and_group;
mod ruler_rule_set_scheduled_evaluation_runs_only_owned_due_groups;

use alerting_rule_dispatch_expands_value_and_labels_templates::alerting_rule_dispatch_expands_value_and_labels_templates;
use alerting_rule_dispatch_sends_firing_alerts_to_alertmanager_sink::alerting_rule_dispatch_sends_firing_alerts_to_alertmanager_sink;
use alerting_rule_dispatch_waits_for_for_duration_before_sending::alerting_rule_dispatch_waits_for_for_duration_before_sending;
use alerting_rule_group_dispatch_runs_alerts_and_skips_recording_rules::alerting_rule_group_dispatch_runs_alerts_and_skips_recording_rules;
use alerting_rule_state_persistence_records_active_and_cleared_alerts::alerting_rule_state_persistence_records_active_and_cleared_alerts;
use alerting_rule_with_compound_for_does_not_fire_immediately::alerting_rule_with_compound_for_does_not_fire_immediately;
use alerting_rule_with_negative_for_is_a_hard_error::alerting_rule_with_negative_for_is_a_hard_error;
use firing_alert_emits_resolved_when_series_stops_matching::firing_alert_emits_resolved_when_series_stops_matching;
use keep_firing_for_holds_alert_firing_then_resolves_after_window::keep_firing_for_holds_alert_firing_then_resolves_after_window;
use labels::labels;
use parse_duration_supports_all_units_and_compounds_and_rejects_bad_input::parse_duration_supports_all_units_and_compounds_and_rejects_bad_input;
use recording_alertmanager_sink::RecordingAlertmanagerSink;
use recording_rule_append_writes_materialized_records_to_sink::recording_rule_append_writes_materialized_records_to_sink;
use recording_rule_evaluation_materializes_float_samples_as_wal_records::recording_rule_evaluation_materializes_float_samples_as_wal_records;
use recording_rule_fails_on_labelset_collision_after_rule_labels::recording_rule_fails_on_labelset_collision_after_rule_labels;
use recording_rule_group_append_runs_recording_rules_and_skips_alerts::recording_rule_group_append_runs_recording_rules_and_skips_alerts;
use recording_rule_merges_rule_level_labels_into_every_series::recording_rule_merges_rule_level_labels_into_every_series;
use recording_ruler_state_sink::RecordingRulerStateSink;
use recording_sink::RecordingSink;
use ruler_alert_state_replays_compacted_records_before_evaluation::ruler_alert_state_replays_compacted_records_before_evaluation;
use ruler_group_state_replays_compacted_last_eval_records::ruler_group_state_replays_compacted_last_eval_records;
use ruler_rule_group_evaluation_appends_recordings_and_dispatches_firing_alerts::ruler_rule_group_evaluation_appends_recordings_and_dispatches_firing_alerts;
use ruler_rule_set_evaluation_persists_group_last_eval_state::ruler_rule_set_evaluation_persists_group_last_eval_state;
use ruler_rule_set_evaluation_runs_namespaced_groups::ruler_rule_set_evaluation_runs_namespaced_groups;
use ruler_rule_set_filter_combines_shard_ownership_and_due_evaluation::ruler_rule_set_filter_combines_shard_ownership_and_due_evaluation;
use ruler_rule_set_filter_keeps_only_groups_due_for_evaluation::ruler_rule_set_filter_keeps_only_groups_due_for_evaluation;
use ruler_rule_set_filter_partitions_groups_by_tenant_namespace_and_group::ruler_rule_set_filter_partitions_groups_by_tenant_namespace_and_group;
use ruler_rule_set_scheduled_evaluation_runs_only_owned_due_groups::ruler_rule_set_scheduled_evaluation_runs_only_owned_due_groups;
