use crate::{
    ActiveLogDeleteFilter, Arc, BTreeMap, BlockDescriptor, CompactionFrontier, FsPath, Int64Array,
    LabelIndex, Labels, MapArray, MetricQuery, MetricWindow, ObjectPath, ObjectStore, QueryError,
    QueryHotTail, QueryRow, RecordBatch, SessionContext, StreamPlan, StringArray, TimeRange,
    UInt64Array, Value, WalLogRecord, append_matching_hot_log_record,
    append_matching_hot_metric_record, append_matching_log_row, apply_absent_over_time, eval_times,
    execute_metric_query_range_from_object_store_with_hot_tail_frontier,
    execute_metric_query_range_from_object_store_with_hot_tail_frontier_and_deletes,
    format_metric_samples, json, loki_matrix_response, metric_plan_scan_sql,
    metric_samples_from_batches, register_log_blocks, register_log_blocks_from_object_store,
    sort_loki_stream_values, structured_metadata_value,
};

// === split-modules: generated submodules ===
mod append_matching_log_batches;
mod collect_object_store_metric_log_batches;
mod execute_metric_query;
mod execute_metric_query_from_object_store;
mod execute_metric_query_from_object_store_with_hot_tail_frontier;
mod execute_metric_query_from_object_store_with_hot_tail_frontier_and_deletes;
mod execute_metric_query_range;
mod execute_metric_query_range_from_object_store;
mod execute_metric_query_range_with_deletes;
mod execute_metric_query_range_with_hot_tail;
mod execute_metric_query_range_with_hot_tail_frontier;
mod execute_metric_query_range_with_hot_tail_frontier_and_deletes;
mod execute_metric_query_with_deletes;
mod execute_metric_query_with_hot_tail;
mod execute_metric_query_with_hot_tail_frontier;
mod execute_metric_query_with_hot_tail_frontier_and_deletes;
mod execute_tail_query;
mod execute_tail_query_with_frontier;
mod execute_tail_query_with_frontier_and_deletes;

pub(crate) use append_matching_log_batches::append_matching_log_batches;
pub(crate) use collect_object_store_metric_log_batches::collect_object_store_metric_log_batches;
pub use execute_metric_query::execute_metric_query;
pub use execute_metric_query_from_object_store::execute_metric_query_from_object_store;
pub(crate) use execute_metric_query_from_object_store_with_hot_tail_frontier::execute_metric_query_from_object_store_with_hot_tail_frontier;
pub(crate) use execute_metric_query_from_object_store_with_hot_tail_frontier_and_deletes::execute_metric_query_from_object_store_with_hot_tail_frontier_and_deletes;
pub use execute_metric_query_range::execute_metric_query_range;
pub use execute_metric_query_range_from_object_store::execute_metric_query_range_from_object_store;
pub(crate) use execute_metric_query_range_with_deletes::execute_metric_query_range_with_deletes;
pub use execute_metric_query_range_with_hot_tail::execute_metric_query_range_with_hot_tail;
pub use execute_metric_query_range_with_hot_tail_frontier::execute_metric_query_range_with_hot_tail_frontier;
pub(crate) use execute_metric_query_range_with_hot_tail_frontier_and_deletes::execute_metric_query_range_with_hot_tail_frontier_and_deletes;
pub(crate) use execute_metric_query_with_deletes::execute_metric_query_with_deletes;
pub use execute_metric_query_with_hot_tail::execute_metric_query_with_hot_tail;
pub use execute_metric_query_with_hot_tail_frontier::execute_metric_query_with_hot_tail_frontier;
pub(crate) use execute_metric_query_with_hot_tail_frontier_and_deletes::execute_metric_query_with_hot_tail_frontier_and_deletes;
pub use execute_tail_query::execute_tail_query;
pub use execute_tail_query_with_frontier::execute_tail_query_with_frontier;
pub(crate) use execute_tail_query_with_frontier_and_deletes::execute_tail_query_with_frontier_and_deletes;
