// Captured independently from Prometheus v0.314.0 template.NewTemplateExpander.
// Source template/template.go SHA256 68eb1a56702a4ac7d97ff3828257b34b222af73780d508870fc7dec7a443d2d9.
// Timestamp1709211845123ms; URL https://prom.example/x%20y?arg=a%2Bb.
pub const CASES: &[(&str, &str, &str, bool)] = &[
    (
        "now_type",
        "printf \"%T:%.3f\" now now",
        "float64:1709211845.123",
        false,
    ),
    ("first", "value (first (query \"metric\"))", "7", false),
    (
        "strvalue",
        "strvalue (first (query \"metric\"))",
        "raw",
        false,
    ),
    (
        "label",
        "label \"job\" (first (query \"metric\"))",
        "b",
        false,
    ),
    (
        "missing_label",
        "label \"missing\" (first (query \"metric\"))",
        "",
        false,
    ),
    (
        "query_type",
        "printf \"%T:%T\" (query \"metric\") (first (query \"metric\"))",
        "template.queryResult:*template.sample",
        false,
    ),
    (
        "args",
        "printf \"%v\" (args \"x\" 2 true)",
        "map[arg0:x arg1:2 arg2:true]",
        false,
    ),
    (
        "regex",
        "reReplaceAll \"(a)(b)\" \"$2$1\" \"abab\"",
        "baba",
        false,
    ),
    (
        "regex_bytes",
        "urlQueryEscape (reReplaceAll \"(.)(.)\" \"$2$1\" \"\\xff\\xfe\")",
        "%FE%FF",
        false,
    ),
    (
        "safe_html",
        "printf \"%T:%s:%q\" (safeHtml \"<b>\") (safeHtml \"<b>\") (safeHtml \"<b>\")",
        "template.HTML:<b>:\"<b>\"",
        false,
    ),
    ("match", "match \"a.+z\" \"a\\nxyz\"", "false", false),
    ("match_rune_error", "match \"�\" \"\\xff\"", "true", false),
    (
        "title",
        "title \"hELLO_world-go it’s a TEST ßeta ﬄower\"",
        "HELLO_world-Go It’s A TEST Sseta Fflower",
        false,
    ),
    (
        "title_double_mid",
        "title \"a''bc a:bc a::bc 1abc\"",
        "A''Bc A:bc A::Bc 1Abc",
        false,
    ),
    ("upper", "toUpper \"straße\"", "STRAßE", false),
    ("lower", "toLower \"İ\"", "i", false),
    (
        "graph",
        "graphLink \"rate(a{job=\\\"x\\\"}[5m])\"",
        "/graph?g0.expr=rate%28a%7Bjob%3D%22x%22%7D%5B5m%5D%29&g0.tab=0",
        false,
    ),
    (
        "table",
        "tableLink \"x+y\"",
        "/graph?g0.expr=x%2By&g0.tab=1",
        false,
    ),
    (
        "sort",
        "range sortByLabel \"job\" (query \"metric\")}}{{label \"job\" .}}={{value .}};{{end",
        "a=2;b=7;b=9;",
        false,
    ),
    (
        "strip_port",
        "stripPort \"[2001:db8::1]:9090\"",
        "2001:db8::1",
        false,
    ),
    ("strip_port_bad", "stripPort \"a:b:c\"", "a:b:c", false),
    (
        "strip_domain",
        "stripDomain \"api.example.com:9090\"",
        "api:9090",
        false,
    ),
    (
        "strip_domain_ip",
        "stripDomain \"[2001:db8::1]:9090\"",
        "[2001:db8::1]:9090",
        false,
    ),
    ("humanize", "humanize \"0.000000000001\"", "1p", false),
    ("humanize_big", "humanize 1e40", "1e+16Y", false),
    ("humanize_zero", "humanize \"-0\"", "-0", false),
    ("humanize1024", "humanize1024 1048576", "1Mi", false),
    ("duration", "humanizeDuration 90061.9", "1d 1h 1m 1s", false),
    ("duration_pico", "humanizeDuration 1e-12", "1ps", false),
    ("duration_zero", "humanizeDuration \"-0\"", "-0s", false),
    ("percentage", "humanizePercentage 0.125", "12.5%", false),
    (
        "timestamp",
        "humanizeTimestamp 1.23456789",
        "1970-01-01 00:00:01.234 +0000 UTC",
        false,
    ),
    ("timestamp_nan", "humanizeTimestamp \"NaN\"", "NaN", false),
    (
        "to_time",
        "printf \"%T:%v\" (toTime 1.23456789) (toTime 1.23456789)",
        "*time.Time:1970-01-01 00:00:01.234 +0000 UTC",
        false,
    ),
    (
        "to_time_method",
        "(toTime 1709211845.123).Year",
        "2024",
        false,
    ),
    (
        "to_duration",
        "printf \"%T:%v\" (toDuration 1.23456789) (toDuration 1.23456789)",
        "*time.Duration:1.23456789s",
        false,
    ),
    (
        "to_duration_inf",
        "toDuration \"Inf\"",
        "-2562047h47m16.854775808s",
        false,
    ),
    (
        "external",
        "externalURL",
        "https://prom.example/x%20y?arg=a%2Bb",
        false,
    ),
    ("path", "pathPrefix", "/x y", false),
    ("parse_duration", "parseDuration \"-1h30m\"", "-5400", false),
    ("parse_duration_zero", "parseDuration \"0\"", "0", false),
    (
        "escape",
        "urlQueryEscape \"\\xff\\x00 é\"",
        "%FF%00+%C3%A9",
        false,
    ),
    ("first_empty", "first (query \"empty\")", "", true),
    ("query_error", "query \"bad\"", "", true),
    ("bad_convert", "humanize true", "", true),
    ("bad_convert_byte", "humanize (index \"x\" 0)", "", true),
    ("bad_timestamp", "toTime \"Inf\"", "", true),
    ("bad_timestamp_overflow", "toTime 1e20", "", true),
    ("bad_float_string", "humanize \"1e400\"", "", true),
    ("bad_duration", "parseDuration \"1s1m\"", "", true),
    ("bad_duration_fraction", "parseDuration \"0.5s\"", "", true),
    ("bad_regex", "match \"[\" \"x\"", "", true),
    (
        "sort_alias",
        "$q := query \"metric\"}}{{$alias := $q}}{{$sorted := sortByLabel \"job\" $q}}{{label \"job\" (first $alias)",
        "a",
        false,
    ),
    (
        "sort_slice_alias",
        "$q := query \"metric\"}}{{$part := slice $q 0 2}}{{$sorted := sortByLabel \"job\" $part}}{{label \"job\" (first $q)",
        "a",
        false,
    ),
    (
        "sort_during_range",
        "$q := query \"metric\"}}{{range $i,$s := $q}}{{label \"job\" $s}}{{if eq $i 0}}{{$sorted := sortByLabel \"job\" $q}}{{end}}{{end",
        "bbb",
        false,
    ),
];
