# krabka-metrics-service --target=ruler
target: ruler
listen: 0.0.0.0:9090
admin-listen-addr: 0.0.0.0:9404
object-store-url: s3://krabka-metrics
manifest-prefix: metrics
wal-bootstrap: broker:9092
wal-client-id: krabka-metrics-ruler
