use std::sync::Arc;

use krabka_blockstore::Labels;

use crate::{
    EngineOpts, ExemplarRecord, InMemoryMetricStore, InstantSample, MergedMetricStore, MetricStore,
    NamedTsdbStat, PromqlEngine, QueryResult, SampleValue, TsdbHeadStats, TsdbStats,
};

// === split-modules: generated submodules ===
mod cardinality_methods_merge_cold_and_hot_series;
mod exemplars_merges_cold_and_hot_records;
mod instant_query_uses_hot_sample_newer_than_compacted_sample;
mod label_names_merges_cold_and_hot_series_metadata;
mod label_values_merges_cold_and_hot_series_metadata;
mod labels;
mod metadata_merges_cold_and_hot_records;
mod min_present_time_preserves_legitimate_zero_min_time;
mod range_query_counts_sample_present_in_both_stores_once;
mod tsdb_blocks_merges_cold_and_hot_blocks;
mod tsdb_stats_ignore_empty_side_min_time;
mod tsdb_stats_merge_cold_and_hot_counts;

use cardinality_methods_merge_cold_and_hot_series::cardinality_methods_merge_cold_and_hot_series;
use exemplars_merges_cold_and_hot_records::exemplars_merges_cold_and_hot_records;
use instant_query_uses_hot_sample_newer_than_compacted_sample::instant_query_uses_hot_sample_newer_than_compacted_sample;
use label_names_merges_cold_and_hot_series_metadata::label_names_merges_cold_and_hot_series_metadata;
use label_values_merges_cold_and_hot_series_metadata::label_values_merges_cold_and_hot_series_metadata;
use labels::labels;
use metadata_merges_cold_and_hot_records::metadata_merges_cold_and_hot_records;
use min_present_time_preserves_legitimate_zero_min_time::min_present_time_preserves_legitimate_zero_min_time;
use range_query_counts_sample_present_in_both_stores_once::range_query_counts_sample_present_in_both_stores_once;
use tsdb_blocks_merges_cold_and_hot_blocks::tsdb_blocks_merges_cold_and_hot_blocks;
use tsdb_stats_ignore_empty_side_min_time::tsdb_stats_ignore_empty_side_min_time;
use tsdb_stats_merge_cold_and_hot_counts::tsdb_stats_merge_cold_and_hot_counts;
