use super::prelude::{BTreeSet, CompactorRunError, HttpQueryError, Labels, check};

mod a_log_pattern_token_masks_only_its_variable_part;
mod a_retained_alert_key_belongs_to_its_rule_and_was_not_just_seen;
mod a_rule_matches_only_when_every_active_filter_accepts_it;
mod a_vector_matching_modifier_reports_where_it_ended;
mod copying_descriptor_labels_refuses_a_series_the_source_cannot_name;
mod logfmt_parser_flags_carry_their_own_leading_space;
mod only_a_number_or_a_vector_function_could_be_a_scalar_vector_expression;
mod patterns_params_require_three_and_take_the_last_of_each;
