use super::prelude::{Bytes, check};

mod a_posted_query_puts_the_url_first_and_the_body_second;
mod a_sample_state_has_samples_from_the_first_one;
mod a_scalar_sample_formats_its_sign_and_stops_at_nine_decimals;
mod a_stale_or_short_shard_range_entry_is_evicted_not_reused;
mod a_vector_group_modifier_reports_what_it_consumed;
mod empty_prometheus_rules_filter_values_are_ignored;
mod every_metric_comparison_operator_maps_to_its_own_variant;
mod merging_sample_states_keeps_the_extremes_and_the_ends;
mod metric_modulo_refuses_a_zero_divisor;
mod metric_values_round_trip_through_their_decimal_scale;
mod recording_samples_keeps_the_earliest_and_the_latest;
mod rules_filters_take_only_the_values_they_recognise;
