use assert2::check;
use krabka_units::convert::TimeExt as _;

use super::prelude::{
    Arc, BTreeMap, BTreeSet, BlockIndex, Bytes, CompactorDeleteState, ComparisonOp,
    ConfiguredObjectStore, DetectedFieldStats, DetectedFieldType, DistributorError, HeaderMap,
    HttpQueryError, KafkaWalHeader, KafkaWalRecord, LabelIndex, Labels, LogDeleteRequestStoreError,
    MetricVectorGroupModifier, MetricVectorMatching, ObjectPath, Offset, PartitionIndex,
    QuerierIndexSource, QuerierState, QueryKind, QueryParams, ServiceConfig,
    SharedLogDeleteRequests, StatusCode, Time, TimeRange, Value,
    apply_metric_binary_comparison_to_loki_result, build_configured_querier_state,
    default_metric_range_step, detect_json_fields, execute_create_delete_request,
    execute_http_query, json, log_delete_requests_path, metric_query_uses_approx_topk,
    metric_query_uses_count_values, parse_metric_query, read_log_delete_requests,
    resolved_range_step, set_remote_parent_from_wal_records, signed_vector_function_literal_error,
    status_metrics, validate_loki_empty_json_value_timestamp_window,
    validate_loki_query_range_resolution, validate_query_range_limit, write_log_index_manifest,
    write_tenant_log_index_manifest_to_object_store,
};

// === split-modules: generated submodules ===
mod a_compaction_batch_is_reparented_into_the_producers_trace;
mod a_created_delete_request_is_stamped_in_whole_seconds;
mod a_dynamic_tenant_index_needs_both_no_tenant_and_a_tenant_index_source;
mod a_group_right_comparison_keeps_the_right_series_it_matched;
mod a_range_step_is_refused_only_when_it_is_not_positive;
mod a_single_tenant_query_still_meets_the_configured_range_limit;
mod a_vector_call_inside_a_string_literal_is_not_a_signed_literal;
mod an_empty_json_value_is_refused_only_when_a_stale_window_is_set;
mod count_values_and_approx_topk_are_recognised_apart_from_each_other;
mod delete_requests_reread_the_file_and_only_tolerate_it_being_absent;
mod json_fields_take_their_detected_type_from_the_json_value;
mod query_range_limits_admit_the_boundary_and_refuse_the_step_past_it;
mod the_status_page_flags_only_the_compactor_as_running;

pub (crate) use a_compaction_batch_is_reparented_into_the_producers_trace::a_compaction_batch_is_reparented_into_the_producers_trace;
pub (crate) use a_created_delete_request_is_stamped_in_whole_seconds::a_created_delete_request_is_stamped_in_whole_seconds;
pub (crate) use a_dynamic_tenant_index_needs_both_no_tenant_and_a_tenant_index_source::a_dynamic_tenant_index_needs_both_no_tenant_and_a_tenant_index_source;
pub (crate) use a_group_right_comparison_keeps_the_right_series_it_matched::a_group_right_comparison_keeps_the_right_series_it_matched;
pub (crate) use a_range_step_is_refused_only_when_it_is_not_positive::a_range_step_is_refused_only_when_it_is_not_positive;
pub (crate) use a_single_tenant_query_still_meets_the_configured_range_limit::a_single_tenant_query_still_meets_the_configured_range_limit;
pub (crate) use a_vector_call_inside_a_string_literal_is_not_a_signed_literal::a_vector_call_inside_a_string_literal_is_not_a_signed_literal;
pub (crate) use an_empty_json_value_is_refused_only_when_a_stale_window_is_set::an_empty_json_value_is_refused_only_when_a_stale_window_is_set;
pub (crate) use count_values_and_approx_topk_are_recognised_apart_from_each_other::count_values_and_approx_topk_are_recognised_apart_from_each_other;
pub (crate) use delete_requests_reread_the_file_and_only_tolerate_it_being_absent::delete_requests_reread_the_file_and_only_tolerate_it_being_absent;
pub (crate) use json_fields_take_their_detected_type_from_the_json_value::json_fields_take_their_detected_type_from_the_json_value;
pub (crate) use query_range_limits_admit_the_boundary_and_refuse_the_step_past_it::query_range_limits_admit_the_boundary_and_refuse_the_step_past_it;
pub (crate) use the_status_page_flags_only_the_compactor_as_running::the_status_page_flags_only_the_compactor_as_running;
