use super::prelude::check;

// === split-modules: generated submodules ===
mod a_repeated_detected_fields_parameter_keeps_the_first_value;
mod a_repeated_detected_labels_parameter_keeps_the_first_value;
mod a_repeated_log_query_parameter_keeps_the_first_value;
mod a_repeated_volume_parameter_keeps_the_first_value;
mod detected_field_types_merge_to_what_still_describes_both;
mod duration_units_are_worth_what_they_should_relative_to_each_other;
mod every_duration_unit_maps_to_its_ordinal_and_bit;
mod logfmt_pairs_split_on_unquoted_whitespace;
mod scalar_samples_compare_as_rationals;

pub (crate) use a_repeated_detected_fields_parameter_keeps_the_first_value::a_repeated_detected_fields_parameter_keeps_the_first_value;
pub (crate) use a_repeated_detected_labels_parameter_keeps_the_first_value::a_repeated_detected_labels_parameter_keeps_the_first_value;
pub (crate) use a_repeated_log_query_parameter_keeps_the_first_value::a_repeated_log_query_parameter_keeps_the_first_value;
pub (crate) use a_repeated_volume_parameter_keeps_the_first_value::a_repeated_volume_parameter_keeps_the_first_value;
pub (crate) use detected_field_types_merge_to_what_still_describes_both::detected_field_types_merge_to_what_still_describes_both;
pub (crate) use duration_units_are_worth_what_they_should_relative_to_each_other::duration_units_are_worth_what_they_should_relative_to_each_other;
pub (crate) use every_duration_unit_maps_to_its_ordinal_and_bit::every_duration_unit_maps_to_its_ordinal_and_bit;
pub (crate) use logfmt_pairs_split_on_unquoted_whitespace::logfmt_pairs_split_on_unquoted_whitespace;
pub (crate) use scalar_samples_compare_as_rationals::scalar_samples_compare_as_rationals;
