use super::prelude::{BTreeMap, Labels, MetricValue, check};

// === split-modules: generated submodules ===
mod a_bytes_literal_needs_a_number_and_a_unit_it_knows;
mod a_loki_duration_composes_only_the_units_it_needs;
mod a_loki_vector_sample_reads_its_value_and_not_its_timestamp;
mod a_prometheus_duration_literal_runs_from_larger_units_to_smaller;
mod a_tail_frame_limit_is_spent_across_streams_in_order;
mod a_tail_holds_back_records_newer_than_its_delay;
mod consuming_a_hot_metric_sample_spends_its_budget_once_per_unit;
mod in_place_vector_arithmetic_reads_the_left_operand_before_writing_it;
