use super::prelude::{BlockIndex, LabelIndex, Labels, QuerierState, SeriesParams, check};

// === split-modules: generated submodules ===
mod a_loki_offset_duration_picks_the_largest_unit_that_fits;
mod a_loki_stream_limit_is_spent_across_streams_in_order;
mod a_scalar_literal_ends_where_the_number_does;
mod decimal_second_timestamps_scale_their_fraction_by_position;
mod formatting_a_logql_query_canonicalises_by_kind;
mod formatting_uses_the_recursive_logql_ast_for_nested_expressions;
mod hex_digits_map_across_all_three_ranges_and_nothing_else;
mod logql_parse_errors_name_the_tokens_loki_clients_expect;
mod metadata_label_sets_are_distinct_filtered_and_stripped;
mod metadata_label_sets_bound_the_hot_tail_to_the_window_and_the_tenant;
mod recursive_formatting_preserves_loki_specific_rejections;
