use super::prelude::{BTreeMap, BTreeSet, BlockIndex, LabelIndex, Labels, check};

// === split-modules: generated submodules ===
mod a_hot_metric_record_lands_in_every_window_that_contains_it;
mod a_label_replace_binary_expression_names_its_own_kind;
mod a_sample_buckets_onto_the_grid_measured_from_the_query_start;
mod counting_index_stats_reads_only_the_rows_a_plan_would;
mod missing_metadata_blocks_fall_back_to_their_indexed_fingerprints;

pub (crate) use a_hot_metric_record_lands_in_every_window_that_contains_it::a_hot_metric_record_lands_in_every_window_that_contains_it;
pub (crate) use a_label_replace_binary_expression_names_its_own_kind::a_label_replace_binary_expression_names_its_own_kind;
pub (crate) use a_sample_buckets_onto_the_grid_measured_from_the_query_start::a_sample_buckets_onto_the_grid_measured_from_the_query_start;
pub (crate) use counting_index_stats_reads_only_the_rows_a_plan_would::counting_index_stats_reads_only_the_rows_a_plan_would;
pub (crate) use missing_metadata_blocks_fall_back_to_their_indexed_fingerprints::missing_metadata_blocks_fall_back_to_their_indexed_fingerprints;
