use krabka_units::convert::TimeExt as _;

use super::prelude::{
    Arc, BTreeMap, BTreeSet, BlockDescriptor, BlockIndex, BlockKey, BufferedLogHotTail,
    CompactionFrontier, InMemoryWalSink, LabelIndex, Labels, LogCompactionIndexOutput, LogHotTail,
    LogWalSink, ObjectPath, ObjectStore, Offset, PartitionIndex, QuerierState,
    RecordingObjectStore, ScalarVectorExpressionResult, SharedCompactionFrontier, TimeRange,
    WalLogRecord, WalPosition, brute_force_in_range, check, hot_tail_test_record, json,
    loki_instant_scalar_or_vector_response, loki_json_timestamp_value_parse_error, minutes,
    parse_detected_labels_params, read_tenant_log_index_shard_ranges_from_object_store,
    refresh_compaction_frontier_and_prune, write_compaction_frontier_to_object_store,
    write_tenant_compaction_indexes_to_object_store,
};

// --- FIX B1 tests ---

// === split-modules: generated submodules ===
mod appending_log_index_shard_does_not_rewrite_historical_shards_or_full_manifest;
mod compaction_frontier_refresh_prunes_hot_tail_from_object_store;
mod compaction_frontier_refresh_treats_absent_manifest_as_empty;
mod detected_labels_empty_query_is_match_all;
mod formats_loki_array_json_timestamp_error_context;
mod formats_loki_numeric_json_timestamp_error_context;
mod formats_loki_object_json_timestamp_error_context;
mod hot_tail_prune_compacted_rebuilds_records_and_time_index;
mod hot_tail_records_in_range_matches_full_scan_under_out_of_order_inserts;
mod instant_scalar_expression_keeps_loki_seconds_timestamp;
mod instant_synthetic_vector_uses_raw_loki_timestamp;
mod querier_state_with_request_tenant_index_tolerates_absent_manifest;
mod querier_state_with_request_tenant_index_tolerates_absent_shards;
mod the_shard_catalog_lists_each_compacted_range_exactly_once;

pub (crate) use appending_log_index_shard_does_not_rewrite_historical_shards_or_full_manifest::appending_log_index_shard_does_not_rewrite_historical_shards_or_full_manifest;
pub (crate) use compaction_frontier_refresh_prunes_hot_tail_from_object_store::compaction_frontier_refresh_prunes_hot_tail_from_object_store;
pub (crate) use compaction_frontier_refresh_treats_absent_manifest_as_empty::compaction_frontier_refresh_treats_absent_manifest_as_empty;
pub (crate) use detected_labels_empty_query_is_match_all::detected_labels_empty_query_is_match_all;
pub (crate) use formats_loki_array_json_timestamp_error_context::formats_loki_array_json_timestamp_error_context;
pub (crate) use formats_loki_numeric_json_timestamp_error_context::formats_loki_numeric_json_timestamp_error_context;
pub (crate) use formats_loki_object_json_timestamp_error_context::formats_loki_object_json_timestamp_error_context;
pub (crate) use hot_tail_prune_compacted_rebuilds_records_and_time_index::hot_tail_prune_compacted_rebuilds_records_and_time_index;
pub (crate) use hot_tail_records_in_range_matches_full_scan_under_out_of_order_inserts::hot_tail_records_in_range_matches_full_scan_under_out_of_order_inserts;
pub (crate) use instant_scalar_expression_keeps_loki_seconds_timestamp::instant_scalar_expression_keeps_loki_seconds_timestamp;
pub (crate) use instant_synthetic_vector_uses_raw_loki_timestamp::instant_synthetic_vector_uses_raw_loki_timestamp;
pub (crate) use querier_state_with_request_tenant_index_tolerates_absent_manifest::querier_state_with_request_tenant_index_tolerates_absent_manifest;
pub (crate) use querier_state_with_request_tenant_index_tolerates_absent_shards::querier_state_with_request_tenant_index_tolerates_absent_shards;
pub (crate) use the_shard_catalog_lists_each_compacted_range_exactly_once::the_shard_catalog_lists_each_compacted_range_exactly_once;
