use krabka_units::convert::TimeExt as _;

use super::prelude::{
    BlockIndex, DistributorError, HttpQueryError, LabelIndex, Labels, Time, check,
};

// === split-modules: generated submodules ===
mod a_decimal_sample_literal_parses_to_an_exact_rational;
mod a_log_level_parameter_names_why_it_was_refused;
mod a_log_level_post_prefers_the_body_over_the_query_string;
mod a_stale_dynamic_index_entry_is_evicted_rather_than_just_missed;
mod scalar_division_and_power_refuse_what_has_no_answer;
mod the_loki_ingestion_window_accepts_its_own_boundaries;

pub (crate) use a_decimal_sample_literal_parses_to_an_exact_rational::a_decimal_sample_literal_parses_to_an_exact_rational;
pub (crate) use a_log_level_parameter_names_why_it_was_refused::a_log_level_parameter_names_why_it_was_refused;
pub (crate) use a_log_level_post_prefers_the_body_over_the_query_string::a_log_level_post_prefers_the_body_over_the_query_string;
pub (crate) use a_stale_dynamic_index_entry_is_evicted_rather_than_just_missed::a_stale_dynamic_index_entry_is_evicted_rather_than_just_missed;
pub (crate) use scalar_division_and_power_refuse_what_has_no_answer::scalar_division_and_power_refuse_what_has_no_answer;
pub (crate) use the_loki_ingestion_window_accepts_its_own_boundaries::the_loki_ingestion_window_accepts_its_own_boundaries;
