use super::prelude::{MetricScalarArithmeticOp, check};

// === split-modules: generated submodules ===
mod a_leading_vector_group_modifier_is_peeled_with_its_labels;
mod a_signed_vector_literal_is_reported_at_the_sign;
mod a_vector_aggregation_renders_only_the_groupings_its_operator_allows;
mod an_alert_fires_once_it_has_held_for_its_configured_duration;
mod an_unspaced_set_operator_is_reported_at_its_own_column;
mod evaluating_one_alert_rule_leaves_the_other_rules_states_alone;
mod every_promql_scalar_operator_parses_to_its_own_variant;

pub (crate) use a_leading_vector_group_modifier_is_peeled_with_its_labels::a_leading_vector_group_modifier_is_peeled_with_its_labels;
pub (crate) use a_signed_vector_literal_is_reported_at_the_sign::a_signed_vector_literal_is_reported_at_the_sign;
pub (crate) use a_vector_aggregation_renders_only_the_groupings_its_operator_allows::a_vector_aggregation_renders_only_the_groupings_its_operator_allows;
pub (crate) use an_alert_fires_once_it_has_held_for_its_configured_duration::an_alert_fires_once_it_has_held_for_its_configured_duration;
pub (crate) use an_unspaced_set_operator_is_reported_at_its_own_column::an_unspaced_set_operator_is_reported_at_its_own_column;
pub (crate) use evaluating_one_alert_rule_leaves_the_other_rules_states_alone::evaluating_one_alert_rule_leaves_the_other_rules_states_alone;
pub (crate) use every_promql_scalar_operator_parses_to_its_own_variant::every_promql_scalar_operator_parses_to_its_own_variant;
