use krabka_units::convert::TimeExt as _;

use super::prelude::{HttpQueryError, Time, check};

// === split-modules: generated submodules ===
mod a_loki_interval_is_refused_only_when_negative;
mod a_loki_query_length_always_writes_all_three_units;
mod a_query_string_splits_only_before_a_known_key;
mod a_request_takes_its_query_from_the_string_before_the_body;
mod a_scalar_vector_expression_must_consume_its_whole_query;
mod a_vector_comparison_records_which_side_the_literal_was_on;
mod loki_vector_timestamps_are_rewritten_from_nanos_to_seconds;
mod missing_loki_rules_are_empty_but_unreadable_ones_are_an_error;
mod series_params_accumulate_matchers_but_keep_the_first_time_bound;

pub (crate) use a_loki_interval_is_refused_only_when_negative::a_loki_interval_is_refused_only_when_negative;
pub (crate) use a_loki_query_length_always_writes_all_three_units::a_loki_query_length_always_writes_all_three_units;
pub (crate) use a_query_string_splits_only_before_a_known_key::a_query_string_splits_only_before_a_known_key;
pub (crate) use a_request_takes_its_query_from_the_string_before_the_body::a_request_takes_its_query_from_the_string_before_the_body;
pub (crate) use a_scalar_vector_expression_must_consume_its_whole_query::a_scalar_vector_expression_must_consume_its_whole_query;
pub (crate) use a_vector_comparison_records_which_side_the_literal_was_on::a_vector_comparison_records_which_side_the_literal_was_on;
pub (crate) use loki_vector_timestamps_are_rewritten_from_nanos_to_seconds::loki_vector_timestamps_are_rewritten_from_nanos_to_seconds;
pub (crate) use missing_loki_rules_are_empty_but_unreadable_ones_are_an_error::missing_loki_rules_are_empty_but_unreadable_ones_are_an_error;
pub (crate) use series_params_accumulate_matchers_but_keep_the_first_time_bound::series_params_accumulate_matchers_but_keep_the_first_time_bound;
