use super::prelude::{BTreeMap, Labels, METRIC_DECIMAL_SCALE, MetricValue, check};

// === split-modules: generated submodules ===
mod a_decimal_seconds_timestamp_scales_its_fraction_to_nanos;
mod a_form_component_decodes_its_escapes_or_refuses_them;
mod a_line_number_counts_from_one_and_clamps_past_the_end;
mod a_metric_square_root_floors_and_refuses_what_has_no_root;
mod a_metric_subtraction_stays_exact_across_denominators;
mod a_metric_value_renders_without_trailing_zeros;
mod a_sample_timestamp_offers_every_reading_its_encoding_allows;
mod a_word_boundary_needs_whitespace_or_an_end_on_both_sides;
mod loki_scan_stats_report_only_the_sources_that_contributed;
mod loki_stream_values_sort_numerically_not_lexicographically;
mod only_a_wholly_parenthesised_expression_is_unwrapped;
mod two_samples_share_an_instant_if_any_reading_of_them_agrees;
